runtime: nodejs22
instance_class: F1

env_variables:
  PORT: "8080"
  FIREBASE_PROJECT_ID: "plan-and-trip-poc"
  FIREBASE_DATABASE_ID: "planandtrippocnative"
  FIREBASE_WEB_API_KEY: "AIzaSyBjcerDXPZmO0i4D_B4QC7DnwWXyPyExOo"
  FAST2SMS_API_KEY: "wMmtIDYHUjxuNhPa21p6dzviqk5GyFBRL34Og7eT9l8EVSb0KoSeZy8Lmcg3lKfid7MYwhJspvrW9Dbx"
  USE_TEXTBELT_FREE: "true"
  TEXTBELT_API_KEY: "textbelt"
